name: Publish Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Linux
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2  
      - uses: subosito/flutter-action@v2
        with:                    
          channel: 'beta'
      
      # Use beta channel
      - run: flutter channel beta
      
      # Upgrade
      - run: flutter upgrade
      
      # Print dart version
      - run: dart --version
      
      # Print flutter version
      - run: flutter --version
      
      # Enable linux as taget platform
      - run: flutter config --enable-linux-desktop
                 
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential pkg-config curl file git unzip xz-utils zip libgtk-3-dev
            
      
      # Build flutter app
      - run: |
          flutter pub get
          flutter build linux
      
      - name: Build AppImage unsing appimage-builder
        uses: docker://appimagecrafters/appimage-builder:0.9.1
        with:
          entrypoint: appimage-builder
          args: --recipe ./AppImageBuilder.yml --skip-test

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: './*.AppImage*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
